### ISSUE TITLE
status_message in sdc_extreme

### ISSUE THREAD

**Issue by tbecker2511** [Plebejer/sdcLog#10]
Bei fehlendem by Argument in sdc_extreme gibt es folgenden Error:
Error in if (!is.null(by) & by != "") { : argument is of length zero

Nach debug liegt Problem in status_message call, bei anderen Funktionen gibt es aber kein Problem.

**Comment by tbecker2511** [comment]
solved, branch: problem_status_message_extreme

**Comment by Plebejer** [comment]
Ich würde es erst als solved markieren, wenn es in den master branch gemerged ist.

**Comment by Plebejer** [comment]
Das Problem lag darin, dass `by` nicht im environment der aufrufenden Funktion substitutiert wurde. Das mit `&&` muss Zufall gewesen sein, sodass du danach kein unquoted `by` mehr angegeben hast.
