### ISSUE TITLE
test sdc_model()

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#11]
- throw helpful error message if model object is not supported

**Comment by tbecker2511** [comment]
Erster Vorschlag für Tests. Hatte überlegt alle Tests nochmal für eine andere Modellform (außer lm) durchzuführen. Wäre das sinnvoll?

**Comment by tbecker2511** [comment]
Außerdem habe ich die Tests so aufgebaut, dass hauptsächlich die return Liste getestet wird. Daher würde eine nachträgliche Änderung in den print methoden keine extrem große Rolle spielen. Frage ist dabei, ob das vorteilhaft ist?

**Comment by tbecker2511** [comment]
Habe nochmal für glm getestet, da laufen die Tests auch wie gewünscht durch. Ist die Frage, ob wir diese Variante nochmal unbedingt im test-Skript benötigen.

**Comment by Plebejer** [comment]
Denke, das ist nicht zwingend nötig. Im Endeffekt würden wir damit ja `broom::augment()` testen.

Was mir aber noch gekommen ist: Wir sollten Tests schreiben, denen wir falsche Argumente übergeben, um zu testen, ob die Fehlermeldungen hilfreich sind.

**Comment by tbecker2511** [comment]
Alles klar! Das würde ich dann gerade noch für tests sdc_model() machen.

**Comment by tbecker2511** [comment]
Ich habe eine erste Version comitted (commit: 0ec1370). In dieser wird geprüft, ob für verschiedene Fälle überhaupt eine Fehlermeldung kommt und anschließend, ob die gewünschte Meldung ausgegeben wird - kann später in einen Test überführt werden. Habe auf zwei Tests zurückgegriffen, um ggf. die Fehlermeldung erst anzupassen und zu testen.
