### ISSUE TITLE
status message (arguments) sdc_model

### ISSUE THREAD

**Issue by tbecker2511** [Plebejer/sdcLog#16]
Bei call von sdc_model wird "by" in "settings" geprinted, obwohl kein by-Argument angegeben ist. 

Beispiel:
```r
sdc_model(model_test_dt, model_1, "id"):
[ SETTINGS: id_var: id | by: by ]
```

**Comment by Plebejer** [comment]
(Hopefully!!) solved with 2317c0e570954d10681b06064bab93c1cd66c356 (gefühlt das 10. Mal, diesmal bin ich aber zuversichtlich, dass es geklappt hat)

Falls nicht, bitte reopen.

Du kannst dir `status_messages()` aus dem `master` branch in deinen branch mergen, damit du mit den Tests weitermachen kannst.

**Comment by tbecker2511** [comment]
Läuft jetzt sauber durch und printed wie gewünscht!
