### ISSUE TITLE
print methods in sdc_model

### ISSUE THREAD

**Issue by tbecker2511** [Plebejer/sdcLog#20]
print.sdc_dominance printed bei model nicht, dass es keine Probleme mit dominance gibt (bei sdc.info_level = 2).

**Comment by Plebejer** [comment]
@tbecker2511: Schau dir mal den branch https://github.com/Plebejer/sdcLog/tree/sdc_model_verbose an. Wäre das eine passende Lösung?

**Comment by tbecker2511** [comment]
So läuft es mittlerweile - jedoch wird für jede Variable einzeln angegeben, wenn es keine Probleme gibt (hier vllt Möglichkeit die Meldung nur einmal bei insgesamt keinen Problemen printen?)

**Comment by Plebejer** [comment]
Dafür müssten wir wahrscheinlich eine neue class mit eigener print method erstellen. `sdc_dominance_list` und `print.sdc_dominance_list`?

**Comment by Plebejer** [comment]
Nach unserem Telefonat gestern habe ich meine Lösung von gestern eben gemerged.
