### ISSUE TITLE
Handling of 0's in the data

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#21]
Wir müssen noch ein Argument einbauen, um unterschiedliches Handling von Nullen zu ermöglichen.

1. Nullen als ganz normaler Wert
1. Nullen als `NA` (als default?)

---

Weitere Fragen:

- Implementierung von Heuristiken, um einen "best guess" zu machen?

**Comment by Plebejer** [comment]
- Betrifft nur `sdc_descriptives()`
- sollte über weiteres Argument gelöst werden: `NA_vals` oder `missing_vals`? (zusätzlich zu `NA`)
- sinnvoller default für das neue Argument?

**Comment by tbecker2511** [comment]
Habe ich wie besprochen umgesetzt (commit: 25e2abb) in neuem branch handling_0. Außerdem habe ich entsprechende Tests dazu geschrieben.

Bisher fehlt noch: "Implementierung von Heuristiken, um einen "best guess" zu machen?"

Sollten wir das noch angehen, bevor ich einen pull request starte?

**Comment by tbecker2511** [comment]
Ich habe nun auch eine Möglichkeit zu best guess hinzugefügt (commit: a3b987b) und einen Test dazu geschrieben. Kannst dir ja mal anschauen, wie du den Vorschlag findest.
