### ISSUE TITLE
sdc_descriptives sollte auf info_level 2 auch Informationen über die einzelnen Ergebnisse zu distinct id's und dominance anzeigen

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#24]
## Beispiel ohne Probleme

- Auf `sdc.info_level` 0: Kein Output
- Auf `sdc.info_level` 1: "Output complies to ..."
- Auf `sdc.info_level` 2: **"No problem with distinct ..." + "No problem with dominance"** + "Output complies to ..."

**Comment by tbecker2511** [comment]
Bereits gelöst in first restructuring? (commit: 1011471)
