### ISSUE TITLE
print() von Objekten mitten in sdc_descriptives /sdc_model sinnvoll?

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#25]
Wäre es besser, die beiden Objekte nicht mitten in der Funktion zu printen, sondern `print.sdc_descriptives()` entsprechend anzupassen?

Gleiches gilt auch für sdc_model.

Bitte um kurze Einschätzung.

**Comment by Plebejer** [comment]
`print.sdc_descriptives()` und `print.sdc_model()` sind bislang nur dafür da, eine Rückmeldung zu geben, wenn alles OK ist. Ist gewissermaßen auch konsistent, aber wenn man die entsprechenden Outputs speichert und später printen möchte, bekommt man nicht des gesamten Output, weil ein Teil schon in den entsprechenden Funktionen geprinted wurde. (Sollte nochmal geprüft werden)

Wenn das stimmt, bin ich dafür die `print()`s mitten in den Funktionen rauszunehmen und dafür die print methoden anzupassen.

**Comment by tbecker2511** [comment]
Also bei sdc_model finde ich es noch passend mit print.sdc_model(). Wenn man nähere Informationen bekommen möchte, kann auch Teil der gespeicherten Liste geprinted werden bspw.:
results <- sdc_model(….)
print results führt zu  "Output complies.."
print results[["distinct_ids"]] führt zu  "No problem with number.."

Falls sich deine Frage darauf bezieht.

Am besten quatschen wir nächste Woche nochmal darüber genau.

**Comment by Plebejer** [comment]
**Ergebnis: Keine prints mehr innerhalb der Funktionen.**

Stattdessen: Mehr Informationen (options, settings) in output von `sdc_descriptives()` und `sdc_model()` und print via jeweilive print method.

**Comment by Plebejer** [comment]
https://github.com/Plebejer/sdcLog/tree/restructuring

**Comment by tbecker2511** [comment]
Auch gelöst mit commit: 63e8a5d ?

**Comment by Plebejer** [comment]
Siehe https://github.com/Plebejer/sdcLog/issues/30#issuecomment-607055876
