### ISSUE TITLE
attach used options and settings to results list

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#28]
Applies to `sdc_descriptives()` and `sdc_model()`.

This enables consistent printing of results no matter if the result is printed to console directly or assigned to an object first.

**Comment by Plebejer** [comment]
https://github.com/Plebejer/sdcLog/tree/restructuring

**Comment by tbecker2511** [comment]
Lösungsvorschlag in commit: a1b5c20

**Comment by Plebejer** [comment]
Warum nutzt du `capture_messages` aus `testthat` hier? Spontan würde ich sagen, dass das nur für die Tests gedacht ist.

**Comment by tbecker2511** [comment]
Mh ja, dachte es ist damit vllt. klarer was passiert und es hat das gewünschte Ergebnise gebracht. Würde dann aber wohl eher auf capture.output von utils zurückgreifen?

**Comment by Plebejer** [comment]
Kannst du nicht einfach

```r
message_options()
message_arguments(id_var, val_var, by)
```
direkt beim erstellen der results Liste aufrufen?

**Comment by tbecker2511** [comment]
Dabei würden die options & settings aber bei Zuweisung nicht richtig in der result-list gespeichert.

**Comment by Plebejer** [comment]
Dann darf das nicht als `message()`, sondern als `character()` in die Liste. Über die print method für das gesamte Objekt kann man es dann als `message()` ausgeben.

**Comment by tbecker2511** [comment]
Habe das mal so angepasst wie du vorgeschlagen hast (commit: d827918)
