### ISSUE TITLE
consistently use distinct_ids instead of counts

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#29]
does not apply to purely internal code

**Comment by Plebejer** [comment]
(muss nur noch gemerged werden)

**Comment by Plebejer** [comment]
https://github.com/Plebejer/sdcLog/tree/restructuring

**Comment by tbecker2511** [comment]
Also sollten hier alle counts durch distinct_ids ersetzt werden? Auch sdc_counts als class geändert werden oder geht es nur um die result list? Oder auch in Funktionen?

**Comment by Plebejer** [comment]
Bisher habe ich nur an die results gedacht, aber die Klasse auch umzubenennen wäre noch besser.

**Comment by tbecker2511** [comment]
Habe alle Änderungen vorgenommen (commit: 122d13d). und auch über devtools::document() im namespace angepasst.
