### ISSUE TITLE
Move warnings from print methods to functions

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#30]
This has the benefit that warnings always appear, when the function is called, no matter if the result was assigned or not.

Also, printig the results object, doest not yield a warning any more.

**Comment by Plebejer** [comment]
https://github.com/Plebejer/sdcLog/tree/restructuring

**Comment by tbecker2511** [comment]
Erster Vorschlag in commit: #63e8a5d

**Comment by Plebejer** [comment]
Sieht erstmal gut aus. Allein am Code ist es aber schwierig, alles vollständig nachzuvollziehen.
