### ISSUE TITLE
changes in print methods lead to test failures

### ISSUE THREAD

**Issue by tbecker2511** [Plebejer/sdcLog#31]
Durch die vorgenommenen Änderungen in print_methods und den result lists failen viele Tests von testthat. Anpassungen an Erwartungen notwendig.

**Comment by tbecker2511** [comment]
Ich würde mich darum kümmern und dabei auch gleich https://github.com/Plebejer/sdcLog/issues/27 bearbeiten.

**Comment by tbecker2511** [comment]
Oder sollten erst die neuen print_methods kontrolliert werden?

**Comment by Plebejer** [comment]
Ich denke, wir sollten versuchen, nicht zu viel in diesen einen Pull Request reinzupacken. Im Code sahen die print methods für mich gut aus und beim anpassen der Tests merkst du ja, ob alles so ist, wie wir es möchten.

**Comment by tbecker2511** [comment]
Okay dann würde ich für die Testanpassungen einen neuen branch aufmachen, oder? 

Diesen pull request (restructuring) verlinke ich dann unter den jeweiligen issues.

**Comment by Plebejer** [comment]
Nein, ich hätte gerne Pull Requests, die sauber sind, in dem Sinne, dass wir auch danach funktionierende Checks und Tests haben. 

Ich meinte nur, dass du die print methods quasi nebenher kontrollierst, wenn du die Tests anpasst.

**Comment by tbecker2511** [comment]
Okay ja gut, dann mache ich das so!

**Comment by tbecker2511** [comment]
Mittlerweile behoben für sdc_model mit commit: 6696d1d und für sdc_extreme mit commit: 61f7629

**Comment by tbecker2511** [comment]
Folgt noch für sdc_descriptives

**Comment by tbecker2511** [comment]
Habe eine Anpassung für descriptives vorgenommen, der letzte Test läuft aber noch nicht wie gewünscht, vllt. kannst du da nochmal drüber schauen (commit: a514975)
