### ISSUE TITLE
sdc_extreme funktioniert nicht richtig mit by

### ISSUE THREAD

**Issue by Plebejer** [Plebejer/sdcLog#7]
Bislang liefert `sdc_extreme()` immer eine `data.table` mit einer Zeile und 5 Spalten. Wenn `by` angegeben wird, müssten mehr Zeilen generiert werden. Momentan ändern sich die Ergebnisse, aber es bleibt bei einer Zeile.

**Comment by tbecker2511** [comment]
Hätte jetzt als output für sdc_extreme() einen data.table, der für die Ergebnisse jeweils eine extra Zeile mit jeweiligen Ergebnissen liefert, sofern by angegeben.  Jedoch habe ich mich gefragt, ob nicht schon vorher ein subset von results_min/max nach by Argument nötig ist, um den spezifischen by overlap nach subsets zu prüfen?

**Comment by Plebejer** [comment]
Grouped head: `DT[, head(.SD), by = Treatment]`

**Comment by Plebejer** [comment]
Solved by bec0e21022f5124efd41132b064aeaa58a6e492e
